use_frameworks!

platform :ios, '9.0'

target 'RMSCocoapodsLibrary_Example' do
  pod 'RMSCocoapodsLibrary', :path => '../'

  target 'RMSCocoapodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
